/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useRef, useEffect, type JSX } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

interface GLTFNodes {
  body: THREE.SkinnedMesh;
  petalos: THREE.Mesh;
  petalos001: THREE.Mesh;
  petalos002: THREE.Mesh;
  mixamorig_Hips: THREE.Bone;
}

interface GLTFMaterials {
  BODY: THREE.MeshStandardMaterial;
  "Material.001": THREE.MeshStandardMaterial;
  "Material.002": THREE.MeshStandardMaterial;
  "Material.003": THREE.MeshStandardMaterial;
}

type MetaAngelProps = JSX.IntrinsicElements["group"] & {
  animationSpeed?: number;
};

export default function MetaAngel({
  animationSpeed = 1,
  ...props
}: MetaAngelProps) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF("/metangel_1.glb");
  const n = nodes as unknown as GLTFNodes;
  const m = materials as unknown as GLTFMaterials;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const action = actions["ArmatureAction"];
    if (action) {
      action.timeScale = animationSpeed;
      action.reset().fadeIn(0.5).play();
    }
    return () => {
      action?.fadeOut(0.5);
    };
  }, [actions, animationSpeed]);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      userData={{
        type: "metaangel",
      }}
    >
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <skinnedMesh
            name="body"
            geometry={n.body.geometry}
            material={m.BODY}
            skeleton={n.body.skeleton}
          />
          <mesh
            name="petalos"
            castShadow
            receiveShadow
            geometry={n.petalos.geometry}
            material={m["Material.001"]}
            position={[305.541, -1.512, -2.327]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="petalos001"
            castShadow
            receiveShadow
            geometry={n.petalos001.geometry}
            material={m["Material.002"]}
            position={[317.81, -0.743, -2.529]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="petalos002"
            castShadow
            receiveShadow
            geometry={n.petalos002.geometry}
            material={m["Material.003"]}
            position={[330.649, -0.177, -3.085]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <primitive object={n.mixamorig_Hips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/metangel_1.glb");
