/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { forwardRef, useImperativeHandle } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

export interface OniricHallwayRef {
  openDoor: () => void;
  closeDoor: () => void;
}

type GLTFResult = GLTF & {
  nodes: {
    Mesh004: THREE.Mesh;
    Mesh004_1: THREE.Mesh;
    frame: THREE.Mesh;
    Mesh005: THREE.Mesh;
    Mesh005_1: THREE.Mesh;
    d2005: THREE.Mesh;
    d2006: THREE.Mesh;
    Mesh008: THREE.Mesh;
    Mesh008_1: THREE.Mesh;
    Mesh009: THREE.Mesh;
    Mesh009_1: THREE.Mesh;
    d2009: THREE.Mesh;
    d2010: THREE.Mesh;
    Mesh012: THREE.Mesh;
    Mesh012_1: THREE.Mesh;
    Mesh001: THREE.Mesh;
    Mesh001_1: THREE.Mesh;
    d2012: THREE.Mesh;
    d2013: THREE.Mesh;
    Mesh014: THREE.Mesh;
    Mesh014_1: THREE.Mesh;
    Mesh015: THREE.Mesh;
    Mesh015_1: THREE.Mesh;
    d2016: THREE.Mesh;
    d2017: THREE.Mesh;
    Mesh018: THREE.Mesh;
    Mesh018_1: THREE.Mesh;
    Pasillo: THREE.Mesh;
    Plane: THREE.Mesh;
    Paredes: THREE.Mesh;
  };
  materials: {
    ["door wood"]: THREE.MeshPhysicalMaterial;
    ["vray hr134.001"]: THREE.MeshPhysicalMaterial;
    Material: THREE.MeshStandardMaterial;
    ["Red Carpet"]: THREE.MeshStandardMaterial;
    ["Wooden wall"]: THREE.MeshStandardMaterial;
  };
};

// type ActionName = "door_close.001" | "door_open";
// type GLTFActions = Record<ActionName, THREE.AnimationAction>;

const OniricHallway = forwardRef<
  OniricHallwayRef,
  React.JSX.IntrinsicElements["group"]
>(function OniricHallway(props, ref) {
  const group = React.useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/OniricHallway.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useImperativeHandle(ref, () => ({
    openDoor: () => {
      // Detener todas las animaciones primero
      Object.values(actions).forEach((action) => action?.stop());

      const action = actions["door_open"];
      if (action) {
        action.reset();
        action.setLoop(THREE.LoopOnce, 1);
        action.clampWhenFinished = true;
        action.play();
      }
    },
    closeDoor: () => {
      // Detener todas las animaciones primero
      Object.values(actions).forEach((action) => action?.stop());

      const action = actions["door_close.001"];
      if (action) {
        action.reset();
        action.setLoop(THREE.LoopOnce, 1);
        action.clampWhenFinished = true;
        action.play();
      }
    },
  }));

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Door_transform" position={[0, 0, 1.026]}>
          <group
            name="door"
            position={[0.39, 1.117, -0.017]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          >
            <mesh
              name="Mesh004"
              castShadow
              receiveShadow
              geometry={nodes.Mesh004.geometry}
              material={materials["door wood"]}
            />
            <mesh
              name="Mesh004_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh004_1.geometry}
              material={materials["vray hr134.001"]}
            />
          </group>
          <mesh
            name="frame"
            castShadow
            receiveShadow
            geometry={nodes.frame.geometry}
            material={materials["door wood"]}
            position={[-0.195, 1.081, 0.009]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          />
        </group>
        <group name="Door_classic002" position={[-5.969, 0, 1.026]}>
          <group
            name="d2004"
            position={[0.39, 1.117, -0.017]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          >
            <mesh
              name="Mesh005"
              castShadow
              receiveShadow
              geometry={nodes.Mesh005.geometry}
              material={materials["door wood"]}
            />
            <mesh
              name="Mesh005_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh005_1.geometry}
              material={materials["vray hr134.001"]}
            />
          </group>
          <mesh
            name="d2005"
            castShadow
            receiveShadow
            geometry={nodes.d2005.geometry}
            material={materials["door wood"]}
            position={[-0.195, 1.081, 0.009]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          />
        </group>
        <group name="Door_classic003" position={[-12.054, 0, 1.026]}>
          <mesh
            name="d2006"
            castShadow
            receiveShadow
            geometry={nodes.d2006.geometry}
            material={materials["door wood"]}
            position={[-0.195, 1.081, 0.009]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          />
          <group
            name="d2007"
            position={[0.39, 1.117, -0.017]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          >
            <mesh
              name="Mesh008"
              castShadow
              receiveShadow
              geometry={nodes.Mesh008.geometry}
              material={materials["door wood"]}
            />
            <mesh
              name="Mesh008_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh008_1.geometry}
              material={materials["vray hr134.001"]}
            />
          </group>
        </group>
        <group name="Door_classic004" position={[-17.946, 0, 1.026]}>
          <group
            name="d2008"
            position={[0.39, 1.117, -0.017]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          >
            <mesh
              name="Mesh009"
              castShadow
              receiveShadow
              geometry={nodes.Mesh009.geometry}
              material={materials["door wood"]}
            />
            <mesh
              name="Mesh009_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh009_1.geometry}
              material={materials["vray hr134.001"]}
            />
          </group>
          <mesh
            name="d2009"
            castShadow
            receiveShadow
            geometry={nodes.d2009.geometry}
            material={materials["door wood"]}
            position={[-0.195, 1.081, 0.009]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          />
        </group>
        <group
          name="Door_classic005"
          position={[-20.017, 0, -0.008]}
          rotation={[Math.PI, -1.562, Math.PI]}
        >
          <mesh
            name="d2010"
            castShadow
            receiveShadow
            geometry={nodes.d2010.geometry}
            material={materials["door wood"]}
            position={[-0.195, 1.081, 0.009]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          />
          <group
            name="d2011"
            position={[0.39, 1.117, -0.017]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          >
            <mesh
              name="Mesh012"
              castShadow
              receiveShadow
              geometry={nodes.Mesh012.geometry}
              material={materials["door wood"]}
            />
            <mesh
              name="Mesh012_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh012_1.geometry}
              material={materials["vray hr134.001"]}
            />
          </group>
        </group>
        <group
          name="Door_classic006"
          position={[-0.019, -0.01, -0.999]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <group
            name="d2001"
            position={[0.39, 1.117, -0.017]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          >
            <mesh
              name="Mesh001"
              castShadow
              receiveShadow
              geometry={nodes.Mesh001.geometry}
              material={materials["door wood"]}
            />
            <mesh
              name="Mesh001_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh001_1.geometry}
              material={materials["vray hr134.001"]}
            />
          </group>
          <mesh
            name="d2012"
            castShadow
            receiveShadow
            geometry={nodes.d2012.geometry}
            material={materials["door wood"]}
            position={[-0.195, 1.081, 0.009]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          />
        </group>
        <group
          name="Door_classic007"
          position={[-5.969, 0, -0.998]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="d2013"
            castShadow
            receiveShadow
            geometry={nodes.d2013.geometry}
            material={materials["door wood"]}
            position={[-0.195, 1.081, 0.009]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          />
          <group
            name="d2014"
            position={[0.39, 1.117, -0.017]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          >
            <mesh
              name="Mesh014"
              castShadow
              receiveShadow
              geometry={nodes.Mesh014.geometry}
              material={materials["door wood"]}
            />
            <mesh
              name="Mesh014_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh014_1.geometry}
              material={materials["vray hr134.001"]}
            />
          </group>
        </group>
        <group
          name="Door_classic008"
          position={[-12.08, 0, -0.998]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <group
            name="d2015"
            position={[0.39, 1.117, -0.017]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          >
            <mesh
              name="Mesh015"
              castShadow
              receiveShadow
              geometry={nodes.Mesh015.geometry}
              material={materials["door wood"]}
            />
            <mesh
              name="Mesh015_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh015_1.geometry}
              material={materials["vray hr134.001"]}
            />
          </group>
          <mesh
            name="d2016"
            castShadow
            receiveShadow
            geometry={nodes.d2016.geometry}
            material={materials["door wood"]}
            position={[-0.195, 1.081, 0.009]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          />
        </group>
        <group
          name="Door_classic009"
          position={[-17.985, 0, -0.998]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="d2017"
            castShadow
            receiveShadow
            geometry={nodes.d2017.geometry}
            material={materials["door wood"]}
            position={[-0.195, 1.081, 0.009]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          />
          <group
            name="d2018"
            position={[0.39, 1.117, -0.017]}
            rotation={[0, 0, Math.PI]}
            scale={-1}
          >
            <mesh
              name="Mesh018"
              castShadow
              receiveShadow
              geometry={nodes.Mesh018.geometry}
              material={materials["door wood"]}
            />
            <mesh
              name="Mesh018_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh018_1.geometry}
              material={materials["vray hr134.001"]}
            />
          </group>
        </group>
        <mesh
          name="Pasillo"
          castShadow
          receiveShadow
          geometry={nodes.Pasillo.geometry}
          material={materials.Material}
          position={[-0.003, 0.002, 0.02]}
        />
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials["Red Carpet"]}
          position={[-0.003, 0.034, 0.007]}
        />
        <mesh
          name="Paredes"
          castShadow
          receiveShadow
          geometry={nodes.Paredes.geometry}
          material={materials["Wooden wall"]}
          position={[-0.003, 0.002, 0.02]}
        />
      </group>
    </group>
  );
});

export default OniricHallway;

useGLTF.preload("/OniricHallway.glb");
